site_name: OpenDutchSolutions
theme:
  name: material
  custom_dir: overrides
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  # - content.footnote.tooltips
  # - content.tabs.link
  - content.tooltips
  # - header.autohide
  # - navigation.expand
  - navigation.footer
  - navigation.indexes
  # - navigation.instant
  # - navigation.instant.prefetch
  # - navigation.instant.progress
  # - navigation.prune
  - navigation.sections
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  # - toc.integrate
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
- blog
markdown_extensions:
- attr_list
- md_in_html

nav:
- index.md
- Blog:
  - blog/index.md
- Projects:
  - Open source projects:
    - projects/open_source/sanbot/sanbot_hardware_overview.md
- About us:
  - about us/about_us.md

# nav:
#   - Blog:
#     - blog/index.md
#   - Projects:
#     - projects/index.md
